default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    adapter: postgresql
    database: <%= ENV.fetch("POSTGRES_DB", "db_dev") %>
    username: <%= ENV.fetch("POSTGRES_USER", "root") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>
    host: postgres
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

  mariadb:
    <<: *default
    adapter: mysql2
    database: <%= ENV.fetch("MYSQL_DATABASE", "db_maria_dev") %>
    username: <%= ENV.fetch("MYSQL_USER", "root") %>
    password: <%= ENV.fetch("MYSQL_PASSWORD", "") %>
    host: mysql
    port: <%= ENV.fetch("MYSQL_PORT", 3306) %>
    migrations_paths: db/mariadb_migrate

test:
  primary:
    <<: *default
    adapter: postgresql
    database: <%= ENV.fetch("POSTGRES_DB_TEST", "db_test") %>
    username: <%= ENV.fetch("POSTGRES_USER", "root") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>
    host: postgres
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

  mariadb:
    <<: *default
    adapter: mysql2
    database: <%= ENV.fetch("MYSQL_DATABASE_TEST", "db_maria_test") %>
    username: <%= ENV.fetch("MYSQL_USER", "root") %>
    password: <%= ENV.fetch("MYSQL_PASSWORD", "") %>
    host: mysql
    port: <%= ENV.fetch("MYSQL_PORT", 3306) %>

production:
  primary: &primary_production
    <<: *default
    adapter: postgresql
    database: <%= ENV.fetch("POSTGRES_DB_PROD", "db_prod") %>
    username: <%= ENV.fetch("POSTGRES_USER_PROD", "user_prod") %>
    password: <%= ENV.fetch("POSTGRES_USER_PROD_PASSWORD") %>
    host: <%= ENV.fetch("POSTGRES_HOST_PROD", "postgres") %> 
    port: <%= ENV.fetch("POSTGRES_PORT_PROD", 5432) %>

  cache:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_DB_PROD_CACHE", "db_prod_cache") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_DB_PROD_QUEUE", "db_prod_queue") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_DB_PROD_CABLE", "db_prod_cable") %>
    migrations_paths: db/cable_migrate

  mariadb:
    <<: *default
    adapter: mysql2
    database: <%= ENV.fetch("MYSQL_DATABASE_PROD") %>
    username: <%= ENV.fetch("MYSQL_USER_PROD") %>
    password: <%= ENV.fetch("MYSQL_PASSWORD_PROD") %>
    host: <%= ENV.fetch("MYSQL_HOST_PROD") %>
    port: <%= ENV.fetch("MYSQL_PORT_PROD", 3306) %>
