---
:concurrency: 5
development:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>
staging:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>
production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>
:queues:
  - [critical, 2]
  - [replication, 5]
  - [default, 1]
